sudo: required
services:
  - docker

before_install:
  - docker build -t sankim/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sankim/react-test npm test

after_success:
  - docker build -t sangmin/multi-client ./client
  - docker build -t sangmin/multi-nginx ./nginx
  - docker build -t sangmin/multi-server ./server
  - docker build -t sangmin/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # Take those images and push them to docker hub
  - docker push sangmin/multi-client
  - docker push sangmin/multi-nginx
  - docker push sangmin/multi-server
  - docker push sangmin/multi-worker
  